FROM apache/airflow:slim-3.2.0b2-python3.11


# Switch to root to install system packages
USER root
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        curl \
        netcat-openbsd \
        gcc \
        g++ \
        && rm -rf /var/lib/apt/lists/*

RUN chmod -R 755 /opt/airflow/dags/ && \
    chown -R airflow:root /opt/airflow/dags/

# Switch back to airflow user
USER airflow

COPY requirements.txt requirements.txt

# Install required providers
RUN pip install apache-airflow==${AIRFLOW_VERSION} -r requirements.txt

# Set environment variables
# ENV AIRFLOW__CORE__LOAD_EXAMPLES=False
# ENV AIRFLOW__WEBSERVER__RBAC=True
# ENV AIRFLOW__API__AUTH_BACKENDS=airflow.api.auth.backend.basic_auth
# ENV AIRFLOW__CORE__AUTH_MANAGER="airflow.providers.fab.auth_manager.fab_auth_manager.FabAuthManager"
# ENV AIRFLOW__WEBSERVER__COOKIE_SAMESITE="None"

# # Copy entrypoint script
# COPY ./scripts/airflow_entrypoint.sh  /entrypoint.sh
# USER root
# RUN chmod +x /entrypoint.sh
# USER airflow

# ENTRYPOINT ["/entrypoint.sh"]



# Create directories
RUN mkdir -p /opt/airflow/dags /opt/airflow/logs /opt/airflow/config

# Copy custom config if exists
COPY config/airflow/airflow.cfg /opt/airflow/airflow.cfg

WORKDIR /opt/airflow